name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify a concrete version for stability
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel setuptools
        # Install git dependencies first
        pip install git+https://github.com/therealjuanmartinez/rich.git@master#egg=rich-13.9.4
    - name: Verify README exists
      run: |
        test -f README.md || (echo "README.md not found" && exit 1)
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m build
        twine check dist/*
        twine upload dist/* 
